### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [10]:
#1
l = []
for i in range(10):
    l.append(i)
print("Metodo classico:",l)
#-----
lc = [i for i in range(10)]
print("List comprehension", lc)

Metodo classico: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
List comprehension [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
#2
l = []
for i in range(30):
    if i%3 ==0:
        l.append(i)
print("Metodo classico:",l)
# ------
lc = [i for i in range(30) if i%3==0]
print("List comprehension", lc)

Metodo classico: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
List comprehension [0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [17]:
#3
l=[]
a= "banana"
for letter in a:
    l.append(letter)
print("Metodo classico:",l)
# -------
lc = [letter for letter in a ]
print("List comprehension", lc)

Metodo classico: ['b', 'a', 'n', 'a', 'n', 'a']
List comprehension ['b', 'a', 'n', 'a', 'n', 'a']


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [30]:
import numpy as np
#creo il vettore
vettore = np.array([2,3,5,7])
print(vettore)
print(len(vettore))
print(vettore.size)
#l'ha memorizzato come int
print(vettore.dtype)

[2 3 5 7]
4
4
int64


In [ ]:
#usando list comprehension
vettore = np.array([
    n for n in range(11) # range dei numeri
    if n>1 and all(n % i !=0 for i in range(2,int(n/2)+1)) # controllo che siano primi
])
print(vettore)

[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [55]:
#creo l'array senza digitarlo
a = np.arange(10)
#prendo una sottostringa e la copio
b = a[2:4].copy()
#faccio il reverse e lo copio
c = a[::-1].copy()
print(f"{a}\n{b}\n{c}")

[0 1 2 3 4 5 6 7 8 9]
[2 3]
[9 8 7 6 5 4 3 2 1 0]


In [61]:
#Divisione di array
print(a[2:10]/c[1:9]) # evito la divisione per zero e il diviso per zero
#senza evitarlo trovo che
print(a/c)

[0.25       0.42857143 0.66666667 1.         1.5        2.33333333
 4.         9.        ]
[0.         0.125      0.28571429 0.5        0.8        1.25
 2.         3.5        8.                inf]


/var/folders/7y/zfcgb0b50ml8l5w4ykdbqc_m0000gn/T/ipykernel_49745/2217373390.py:4: RuntimeWarning: divide by zero encountered in divide
  print(a/c)


In [73]:
#con le liste
a = [i for i in range(10)]
b = a[2:4]
c = a[::-1]
print(a,b,c, sep = "\n")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [84]:
#divisione di array
e = a[1:]
f = c[:-1]

d = [x/y for x,y in zip(e,f)]

print(d)

[0.1111111111111111, 0.25, 0.42857142857142855, 0.6666666666666666, 1.0, 1.5, 2.3333333333333335, 4.0, 9.0]
