# Continuazione Numpy

### Inidcizzazione booleana
Posso selezionare gli elementi di un array utilizzando operatori logici


In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

a>5, a[a>5], np.any(a>5), np.all(a>5)

(array([False, False, False, False, False,  True,  True,  True, False,
        False, False, False, False]),
 array([6, 7, 6]),
 np.True_,
 np.False_)

In [2]:
# Supponiamo di lavorare con dati sulle vendite di automobili, 
# di avere il valore di tutte le auto vendute lo scorso anno
# E di voler identificare le vendite superiori a **30.000$**.  

vendite = np.array([34_255, 27_222, 42_250, 12_000])
vendite

array_vero_falso = vendite > 30_000
array_valori_veri = vendite[vendite > 30_000]

array_vero_falso, array_valori_veri

(array([ True, False,  True, False]), array([34255, 42250]))

> Quindi scrivendo senza [] ottengo un array di true o false, mendre se uso la condizione nel indice ottengo gli elementi che la soddisfano

### Where
- *np.where* controlla gli elementi in base a una condizione e assegna un valore se la condizione è vera o falsa
- Sintassi: *np.where(condition, x, y)*.
- Viene comunemente utilizzato per **sostituire** condizionalmente elementi di un array.

In [3]:
vendite = np.array([34_255, 27_222, 42_250, 12_000])

np.where(vendite>30000)

(array([0, 2]),)

In [4]:
np.where(vendite>30000)[0]

array([0, 2])

> Esempio, nel quale cambiamo valore:

In [5]:
salary_array = np.where(vendite < 30000, 30000, vendite)
salary_array

array([34255, 30000, 42250, 30000])

## Operazioni matematiche
- Funzioni aggregate:
    - sum: somma
    - prod: prodotto
    - cumsum: somma cumulativa
    - cumprod: prodotto cumulativo
- Operazioni matematiche (non approfondiremo questo argomento durante il corso):
    - sqrt
    - exp
    - log
    - sin
    - cos

In [7]:
import random 

salary = [random.randint(100000, 150000) for num in range(10)]

salary

[110194,
 143236,
 143829,
 120648,
 135766,
 133170,
 141100,
 148140,
 101931,
 133759]

In [8]:
#ora lo convertiamo in un array numpy
salary_arr = np.array(salary)
salary_arr

array([110194, 143236, 143829, 120648, 135766, 133170, 141100, 148140,
       101931, 133759])

In [10]:
# Vediamo la SOMMA

sum_salary = np.sum(salary_arr)
sum_salary

np.int64(1311773)

In [11]:
# PRODOTTO
prod_salary = np.prod(salary_arr)
prod_salary

np.int64(7835361236207415296)

In [ ]:
# SOMMA CUMULATIVA
cumsum_salary = np.cumsum(salary_arr)
cumsum_salary # il primo elemento è la somma cumulativa del primo elemento, 
# il secondo elemento è la somma dei primi due ...

array([ 110194,  253430,  397259,  517907,  653673,  786843,  927943,
       1076083, 1178014, 1311773])

In [14]:
# PRODOTTO CUMULATIVO
cumprod_salary = np.cumprod(salary_arr)
cumprod_salary

array([              110194,          15783747784,     2270160660024936,
       -2810817794954795712, -5694097003300355200,  7410708470236294912,
       -2722667884721269760,  2038729050443837440,  7118850452695142400,
        7835361236207415296])


Nota: A causa dei numeri elevati, i valori del prodotto cumulativo aumentano rapidamente fino a superare il limite numerico per i tipi di dati tipici in Python, causando un overflow degli interi.
Per questo motivo, alcuni numeri possono apparire come negativi.

### Prodotto scalare e vettoriale

In [15]:

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Prodotto scalare (dot product)
dot_product = np.dot(v1, v2)  
dot_product2 = v1 @ v2

# Prodotto vettoriale (cross product)
cross_product = np.cross(v1, v2)

dot_product, dot_product2, cross_product

(np.int64(32), np.int64(32), array([-3,  6, -3]))

## Operazioni statistiche

- mean: media
- median: mediana
- var: varianza
- std: deviazione standard
- min: valore minimo
- max: valore massimo

In [38]:
# MEDIA

average_salary = np.mean(salary_arr)
average_salary

np.float64(131177.3)

In [39]:
# MEDIANA

median_salary = np.median(salary_arr)
median_salary

np.float64(134762.5)

In [40]:
# VARIANZA

salary_variance = np.var(salary_arr, ddof = 1) # ddof=1 per la varianza campionaria
salary_variance

np.float64(236652691.34444442)

In [41]:
# DEVIAZIONE STANDARD
salary_std_dev = np.std(salary_arr, ddof = 1) #ddof = 1 per la deviazione std campionaria
salary_std_dev

np.float64(15383.52012201513)

In [42]:
# MIN

min_salary= np.min(salary_arr)

# MAX

max_salary = np.max(salary_arr)

min_salary, max_salary

(np.int64(101931), np.int64(148140))

##### argmax ed argmin
Ritornano gli indici della prima occorrenza dell'elemento massimo/minimo nell'array salary_array.

In [43]:
np.argmax(np.array([1,3,3,3,10]))

np.int64(4)

In [44]:
#attenzione a questo tipo di errore
salary_with_none = np.array([123124, None, 145000, 128000, 110000, 149999,  None, 135000, 115000, 140000])
salary_with_none * 10

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

#### NaN

Posso generare valori NaN usando **np.nan** .Il valore np.nan è utilizzato in NumPy (e, per estensione, in Pandas) per rappresentare dati mancanti o indefiniti.
Utile perché:
- Gestisce i dati mancanti.
- Aiuta nei calcoli, poiché non genera errori ma restituisce np.nan.
- Permette di filtrare o riempire i dati mancanti usando metodi che utilizzeremo spesso nella libreria pandas, come dropna(), fillna(), isna(), o notna().

In [45]:
salary_with_nan = np.array([123124, np.nan, 145000, 128000, 110000, 149999, np.nan, 135000, 115000, 140000])
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

In [ ]:
#posso sostituire valori esistenti con np.nan, per es.: outlier, valori non validi

salary_with_nan[salary_with_nan < 130000] = np.nan
salary_with_nan * 10

(array([     nan,      nan, 1450000.,      nan,      nan, 1499990.,
             nan, 1350000.,      nan, 1400000.]),
 np.float64(nan))

## Generare numeri casuali
La funzione **np.random.normal** estrae campioni casuali da una distribuzione normale:
- Negli argomenti posso specificare:
    - loc : è la media della distribuzione normale
    - scale: deviazione standard
    - size numero di camipioni da generare
Conosciamo anche altre funzioni di campionamento casuale:
    - np.random.rand (uniforme [0,1) )
    - np.random.randn (normale, media 0 e dev st = 1)
    - np.random.randint (uniform con estremi da specificare [) )
    - np.random.random
    - np.random.uniform
    - np.random.binomial
    - np.random.poisson

> attenzione se uso np.random.randint genero in intervalli [) invece se uso random.randint genero in intervalli []

In [51]:
# Generare numeri basati su una distribuzione normale
noise = np.random.normal(0, 5000, salary_array.size)

# Aggiungere questi numeri all'array degli stipendi
salary_array_with_noise = salary_array + noise

salary_array, noise, salary_array_with_noise

(array([34255, 30000, 42250, 30000]),
 array([ 4069.26913285, -2243.26986866, -6057.69131552,  6752.54540609]),
 array([38324.26913285, 27756.73013134, 36192.30868448, 36752.54540609]))

C'è anche una nuova interfaccia per la generazione di array casuali, più adatta al multi-threading, un po' più veloce, più configurabile:

rng = np.random.default_rng()

Tutte con il prefisso rng

Come posso comparare numeri float?
1. np.isclose permette di confrontare float tenendo conto di un margine di tolleranza.

In [52]:
a = np.array([0.1 + 0.2, 0.3])
b = np.array([0.3, 0.3])

a == b, np.isclose(a, b)

(array([False,  True]), array([ True,  True]))

In [53]:
# posso anche scegliere con che tolleranza controllare
np.isclose(a, b, atol=1e-6) #absolute tolerance, errore massimo accettabile.

array([ True,  True])

In [54]:
#tolleranza relativa
a = np.array([1000.0, 0.00001, 50000.0])
b = np.array([1000.1, 0.000011, 50001.0])

np.isclose(a, b, rtol=1e-4)  #relative tolerance, errore relativo rispetto ai valori confrontati.

array([ True, False,  True])

# Caricare e Salvare file in numpy
Inaspettatamente NumPy fornisce diverse funzioni per caricare dati da file, tra cui np.loadtxt, np.genfromtxt e np.load

In [ ]:
#non so dov'è il file ma in teoria lo legge
passeggeri = np.loadtxt('../../dati/data.csv', delimiter=",", dtype=str)
passeggeri

In [57]:
# Generazione di 200 valori casuali di emissioni di CO2 in tonnellate per anno 
# Supponiamo emissioni tra 4 e 20 tonnellate per persona 
co2_emissions = np.round(np.random.uniform(4, 20, 200), 2)

# Nome del file di output
output_file = "emissioni.txt"

# Salvataggio su file
np.savetxt(output_file, co2_emissions, fmt="%.2f")

# Restituisco il percorso del file
output_file

'emissioni.txt'

### Lavorare con matrici
Inizializzazione simile ai vettori

In [58]:
# Creazione di array bidimensionali (matrici)
matrice = np.array([[1, 2, 3], [4, 5, 6]])
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# .shape mi da le dimensioni della matrice
matrice.shape

(2, 3)

In [60]:
# Creare un array bidimensionale di zeri:
zero_2d = np.zeros((3, 2))
print(zero_2d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [76]:
# Creazione di una mtrice di uni
ones_2d = np.ones((1, 3, 4)) # (numero matrici, righe, colonne)
print(ones_2d), print(np.ones((3,3)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


(None, None)

In [63]:
#Creare una matrice con valori casuali:
random_2d = np.random.rand(2, 3)
print(random_2d)

[[0.61532543 0.5380241  0.99264131]
 [0.95440721 0.03754762 0.54880477]]


In [64]:
# Creare una matrice con arrange e shape
np.arange(20).reshape((4, 5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
#selezione indici
a = [[1,2,3], [4,5,6]]
a[0][-1]

3

In [67]:
# posso anche selezionare più elementi di una matrice
a = np.array([[10, 20, 30], 
              [40, 50, 60], 
              [70, 80, 90]])

righe = np.array([0,0, 2, 2])  # Seleziona la riga 0 e la riga 2
colonne = np.array([1,2,1, 2])  # Seleziona la colonna 1 e la colonna 2
# NumPy prende il primo elemento di righe e il primo di colonne per formare la prima coordinata
# poi il secondo con il secondo, e così via.
a[righe, colonne] 

array([20, 30, 80, 90])


## Il concetto di Axis in NumPy

In molte operazioni, come la somma, è necessario specificare a NumPy se l'operazione deve essere eseguita sulle righe o sulle colonne.
Per avere una notazione universale che funzioni con un numero arbitrario di dimensioni, NumPy introduce il concetto di asse (axis).

- Il primo indice corrisponde a axis=0.
- Il secondo indice corrisponde a axis=1, e così via.

Nel caso di un array 2D:

- axis=0 opera sulle colonne
- axis=1 opera sulle righe

In [68]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.sum(), a.sum(0), a.sum(axis=1)

(np.int64(21), array([5, 7, 9]), array([ 6, 15]))

#### Operazioni tra matrici

In [ ]:
np.array([[1, 2], [3, 4]])/100 #divide ogni elemento

array([[0.01, 0.02],
       [0.03, 0.04]])

In [70]:
# addizione e sottrazione tra array
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B
print(C)

D = A - B
print(D)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [71]:
# moltiplicazione elemente per elemento
E = A * B
print(E)

[[ 5 12]
 [21 32]]


In [72]:
# trasposizione 
H1 = A.transpose()
H2 = A.T
print(A,"\n H1:", H1,"\n H2:", H2)

[[1 2]
 [3 4]] 
 H1: [[1 3]
 [2 4]] 
 H2: [[1 3]
 [2 4]]


In [73]:
# inversione 
I = np.linalg.inv(A)
print(I)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [74]:

# Creazione di array tridimensionali
array_3d = np.array([[[ 1,  2,  3],  [ 4 , 5 , 6]]

,[[ 7,  8 , 9],
  [10, 11 ,12]]

 ,[[13, 14, 15],
  [16, 17, 18]]])

array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [75]:
# Creazione di array tridimensionali di uni
ones_3d = np.ones((2, 3, 4))
print(ones_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [77]:
#Creare un array tridimensionale con valori casuali:
random_3d = np.random.rand(2, 3, 4)
print(random_3d)

[[[0.4700015  0.51865484 0.41198532 0.47249688]
  [0.60027422 0.50845202 0.86548957 0.76899212]
  [0.17644969 0.25151673 0.54304069 0.79015623]]

 [[0.24356022 0.34505981 0.93192986 0.14060971]
  [0.02033879 0.84670305 0.91140234 0.45463749]
  [0.10400089 0.50807006 0.76487661 0.62477802]]]


## Broadcasting
Consente di eseguire operazioni tra array di forme diverse senza doverli ridimensionare manualmente. Invece di ripetere i dati più volte per adattare le forme, NumPy espande automaticamente gli array in modo efficiente.

Per applicare il broadcasting, NumPy segue queste tre regole:

1. Se una dimensione è 1, viene replicata per adattarsi all'altra dimensione.

In [78]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])  # (2,3)

B = 10  # Scalare

A + B

array([[11, 12, 13],
       [14, 15, 16]])

2. Se gli array hanno dimensioni diverse, quello più piccolo viene espanso.

In [79]:
A = np.array([10, 20, 30])  # (3,) → Array 1D con 3 elementi
B = np.array([[1], [2], [3]])  # (3,1) → Array 2D con 3 righe e 1 colonna

A + B #Quando sommiamo A + B, NumPy espande A a (3,3) per adattarlo alla forma di B e similmente per B

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

3. Se le dimensioni non sono compatibili e nessuna è 1, il broadcasting fallisce

In [80]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])  # (2,3)

B = np.array([10, 20])  # (2,)

A + B  # Errore! Le dimensioni non sono compatibili.

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### Vectorization
La vettorizzazione del codice è una tecnica che permette di scrivere codice più veloce e leggibile.
Consiste nell'eseguire operazioni su un insieme di valori contemporaneamente, anziché iterare esplicitamente sugli elementi uno per uno con un ciclo.

In [81]:
a = np.arange(1000000) 
b = np.arange(1000000)

In [82]:
%%timeit
# Approccio non vettorizzato con un ciclo for
c = []  # Iniziamo con un array vuoto che popoleremo nel ciclo
for i in range(len(a)):
    c.append(a[i] + b[i])

166 ms ± 4.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [83]:
%%timeit
# Approccio vettorizzato
c = a + b

1.47 ms ± 39.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
