Prima lezione, abbiamo celle markdown, che sono queste

In [1]:
"QUesta è una cella python"

'QUesta è una cella python'

Stampa solo l'ultima riga a meno che tu non usi print

In [2]:
#ES
1+1
"Ciao"
print(3)
2+2

3


4

Come al solito ho vari comandi in markdown:
# Titolo
**grassetto**
*italico*
> blockquote
1. First item
2. Second item
3. Third item
- First item
- Second item
- Third item
`code`
---
e altri per immagini, tabelle e tutto ciò che desideri
°

In [4]:
!ls # con ! lancio comandi shell
%cd #comando magic sulla riga
%%cd # comando magic sulla cella


README.md      esercizi1      hello.py       lezione1.ipynb prova.ipynb
[Errno 2] No such file or directory: '#comando magic sulla riga'
/Users/gabrielalfeo/Desktop/Git/ProgrammingLab


UsageError: Line magic function `%%cd` not found.


# Parte 2 (Python) 

## Guida di Stile

### L'indentazione è importantissima.
Pyhton usa l'indentazione per indicare un blocco di codice

### I :
Alla fine di ogni struttura devo avere i :

### Spazi
Attenzione agli spazi aggiuntivi, che molte volte non sono richiesti

### Commenti
Sempre usare commenti, ci sono più tipi, quelli su una riga #, quelli in linea # e quelli su più righe (blocchi ## o docstring """)

### Funzioni diverse
 - Lambda -> piccole funzioni di una sola espressione
 >lambda argomenti: espressione
 - Built-in -> già in python
 - Definite dall'utente -> def...
 - Dei moduli -> es. math.sqrt()
 - Da librerie esterne -> numpy.array()

## Moduli
È un file che contiene un insieme di funzioni che vuoi includere.

In [16]:
import random # modulo random
random.randint(0,1)

0

Posso anche decidere di importare specifiche funzioni

In [17]:
from random import randint

randint(0,10)

4

Creare un Modulo in Python

- Per creare un modulo in Python, è necessario salvare il codice in un file con estensione .py.

- Nei Jupyter Notebook, il metodo per salvare un modulo è leggermente diverso:

  - Questo metodo ci permette di salvare il contenuto di una cella come file Python con estensione .py.
  - Perché facciamo questo?
    I file Python script (.py) sono file autonomi, mentre i Jupyter Notebook sono organizzati in celle.
  - Come fare? Usando il comando:
  Il comando:
  %%writefile nome_file.py
  permette di scrivere il contenuto della cella in un file nome_file.py e salvarlo nella directory corrente


Utilizzare il Modulo Creato

Note

Per utilizzare una funzione da un modulo, usa la sintassi:

module_name.function_name

## Librerie
Una libreria è una raccolta di pacchetti o singoli moduli che vengono raggruppati per estendere le funzionalità.
Tipologie:
Librerie standard (incluse in Python)
Librerie e pacchetti di terze parti (devono essere installati)
Di solito vengono installate tramite gestori di librerie come pip o cond

### Pachetti
Un pacchetto può includere moduli e sotto-pacchetti. Non è più obbligatorio dopo Python 3.3 ma di solito contiene un file init.py (che lo identifica come pacchetto Python).
mypackage/ │── init.py │── module1.py │── module2.py

Per importare usiamo sempre le parole chiave import e from. Possiamo importare con alias ovvero
> *import* pandas *as* pd

Con il comando %conda list, trovo tutti i pacchetti installati

# NumPy


Sta per NUmerical Python, usata per il calcolo numerico scientifico e l'analisi dati. 

In [18]:
#importiamolo
import numpy as np

In [21]:
# creo una lista di 1,000,000 numeri random tra 50,000 e 150,000
import random
import statistics as stat

lista_numeri = [random.randint(50000, 150000) for _ in range(1000000)]


In [22]:
%%timeit

stat.mean(lista_numeri)

72.6 ms ± 102 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
%%timeit

np.mean(lista_numeri)

16.2 ms ± 24 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
stat.mean(lista_numeri), np.mean(lista_numeri)

(100012.905716, np.float64(100012.905716))

## ndarrray
La struttura dati fondamentale di NumPy è l’ndarray: un array n-dimensionale omogeneo che consente di rappresentare e manipolare insiemi di dati numerici in modo veloce ed efficiente.

Il bello è che la maggior parte delle operazioni sembrano esattamente le stesse, indipendentemente dal numero di dimensioni di un array. Ma i casi 1D e 2D sono un po' speciali.

### Numpy array vs Python array

* Entrambi servono come contenitori
* Più compatti, soprattutto quando le dimensioni sono più di una
* Più veloci delle liste quando l’operazione può essere vettorizzata
* Più lenti se la loro dimensione deve essere continuamente modificata (e.g. append)
* Generalmente omogenei: possono funzionare velocemente solo con elementi di un unico tipo

Li creo da una lista python usando np.array(lista)

In [37]:
# Esempio: Un array di una lista 
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [38]:
np.array([1, 2.2, 3, 4, 5]).dtype # mi dice come numpy ha memorizzato l'array

dtype('float64')

In [39]:
a = np.array([1, 2, 3, 4, 5])
a.dtype

dtype('int64')

In [40]:
np.array([1, 2, 3, 4, "s"]).dtype

dtype('<U21')

Il prefisso U indica che il tipo di dato è una stringa Unicode. Il numero 21 indica la lunghezza massima della stringa in caratteri (21 caratteri in questo caso)

Perché NumPy ha scelto U21?

NumPy cerca di assegnare un unico tipo di dato all'intero array. Dato che uno degli elementi è una stringa ("s"), NumPy converte tutti gli altri elementi (numeri interi) in stringhe per mantenere uniformità. Il valore massimo della lunghezza delle stringhe nel vettore determina il numero (21 in questo caso, ma può variare).

Infatti, esiste una gerarchia dei tipi di dati, in cui un tipo più in basso nella gerarchia può sempre essere convertito in uno più alto, ma non viceversa.

Questa gerarchia è la seguente:

Booleano → Intero → Virgola mobile (float) → Stringa

Quando compaiono oggetti arbitrari come dizionari, liste, tuple, ecc., NumPy spesso passa a object.

In [41]:
np.array([1.,{}, "hello"]).dtype

dtype('O')

In [42]:
# posso esplicitare il tipo che voglio nel mio array
as_a_float = np.array([1, 2], dtype="float")
as_a_float

array([1., 2.])

a.shape ritorna una tupla con le dimensioni dell’array (con un elemento nel caso di un vettore, due per le matrici, etc)

a.size ritorna il numero di elementi totali (e.g., una matrice 4x3 avrà  12 elementi e shape (4,3))

Con a.astype(nome_tipo) possiamo convertire al tipo numpy indicato

In NumPy ci sono due funzioni per l'inizializzazione di array con una sequenza monotona

In [43]:
# arange
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


La funzione arange è sensibile al tipo: se si forniscono int come argomenti, verranno generati int, mentre se si forniscono float verranno generati float.

Linspace è immune agli errori di arrotondamento e genera sempre il numero di elementi richiesti, però conta i punti, non gli intervalli, quindi l'ultimo argomento è sempre più uno rispetto a quello che normalmente penseresti.

In [45]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0,1,11) # attenzione

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Gli array NumPy non possono crescere come un elenco Python: non viene riservato alcuno spazio alla fine dell'array per facilitare aggiunte rapide.

Quindi è una pratica comune far crescere un elenco Python e convertirlo in un array NumPy quando è pronto o preallocare lo spazio necessario con np.zeros o np.empty:

In [50]:

# Creare un array di zeri:
zero_3d = np.zeros((3))
print(zero_3d)

[0. 0. 0.]


## Operazioni di base

In [63]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [64]:

a = np.array([1,2,3,4,5])
a_più_uno = a + 1
a_meno_uno  = a  - 1
a_diviso_due = a/2
a_per_due = a*2
a_più_uno, a_meno_uno, a_diviso_due, a_per_due  

(array([2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4]),
 array([0.5, 1. , 1.5, 2. , 2.5]),
 array([ 2,  4,  6,  8, 10]))

In [65]:
#Lo slicing funziona come per le liste e stringhe
a = np.arange(1,6)
a[3]

np.int64(4)

In [ ]:
#!!! A differenza delle liste gli array non possono essere 
# copiati usando lo slicing
a = [1,2,3]
b = a[3]
b

[1]

In [4]:
# Example: Selecting the experience requirement for the second and third job listings.
b = a[1:3]
c = a[2:0:-1]
a, b, c

([1, 2, 3], [2, 3], [3, 2])

Le assegnazioni non devono modificare la dimensione dell'array, quindi trucchi come:       
  a = [1,2,3].   
  a[1:2] = [5,6].   
  a diventa = a [1,5,6,3].   
  Non funzionerà in NumPy. 
 